# Generated by Django 2.2.3 on 2019-07-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('guest_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_team_set', to='team_stats.TeamStats')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team_stats.TeamStats')),
            ],
        ),
    ]
