# Generated by Django 2.2.3 on 2019-07-12 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possession', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('shots_on_target', models.IntegerField()),
                ('passes', models.IntegerField()),
                ('pass_accuracy', models.IntegerField()),
                ('fouls', models.IntegerField()),
                ('yellow_card', models.IntegerField()),
                ('red_card', models.IntegerField()),
                ('corners', models.IntegerField()),
                ('offsides', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.Team')),
            ],
        ),
    ]
