# Generated by Django 2.2.3 on 2019-07-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='role',
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('FB', 'Full-Back'), ('WB', 'Wing-Back'), ('CD', 'Central Defender'), ('CC', 'Centre Back'), ('S', 'Sweeper'), ('CM', 'Central Midfield'), ('WM', 'Wide Midfield'), ('WW', 'Wide Winger'), ('SF', 'Striker Forward'), ('CF', 'Centre Forward'), ('CF', 'Centre Forward')], default='FB', max_length=10),
        ),
    ]
