# Generated by Django 2.2.3 on 2019-07-08 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0003_auto_20190708_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.Person')),
                ('title', models.CharField(choices=[('M', 'Manager'), ('GM', 'General Manager')], max_length=3)),
            ],
            bases=('players.person',),
        ),
    ]
